### PR TITLE
Support next by distance and label as number

### PR DESCRIPTION
**Pull request by JezPrime-trp**
This pull request adds the following capabilities to the qoomon extension

1. Ability to extract a number from the label (if the label is numeric) – note that this needs to be used with care as a non-numeric label fed into this will cause a build failure – this is because we wish to use (on master) versions of the form 1.2.3-456 (where 456 is auto-generated based on previous build number – more on this shortly)
2. As well as “next” for each property, a “next by distance” where the value is incremented by the distance since the last matching tag. If there is no matching tag then the total number of commits on the repository is used instead.

I have a few notes/queries relating to this. 

We originally did this against an older version of the gradle plugin and I have some tests (which mainly exercised the describe functionality which we added as you have added it more recently) but which covered usage of the placeholders. I notice that you don’t explicitly test usage of placeholders, but I will be very happy to add tests specifically around these placeholders if desired – I was trying to stay close to the existing conventions. Please just let me know if this is preferred.

Secondly, I notice that you have “version.label” but “describe.version.version.label” – is this intentional? My submission currently assumes the inconsistency was unintentional and I’ve changed to “describe.version.label” but again will be happy to revert this piece and make the new properties consistent with “describe.version.version.label” – again please just let me know.

Finally, outside the scope of the functionality, I updated the README to refer to the current version of the extension.

### CODE REVIEW

**Comment by qoomon** [comment]
Related to https://github.com/qoomon/gradle-git-versioning-plugin/pull/86#issuecomment-1185344217

**Comment by JezPrime-trp** [comment]
I'll be applying your suggestions for the equivalent gradle plugin PR here as well, will let you know here when ready for review (no point in repeating yourself unnecessarily)

**Comment by JezPrime-trp** [comment]
I've updated changes from discussions on https://github.com/qoomon/gradle-git-versioning-plugin/pull/86 to this PR too. Please let me know if you have any other suggestions for improvement.

**Comment by JezPrime-trp** [comment]
I've pushed further changes following our discussions on the gradle PR at https://github.com/qoomon/gradle-git-versioning-plugin/pull/86

**Review by qoomon — APPROVED** [review]

**Pull request merged**
