### PR TITLE
Fix Github shell syntax, add notes for using PRs in Github Actions

### PR DESCRIPTION
**Pull request by chris-mac**

### CODE REVIEW

**Comment by qoomon** [comment]
thx for the adjustment

**Comment by qoomon** [comment]
@chris-mac your branch configuration for pull branches can be simplified to
```xml
    <branch>
         <pattern>pull/.+</pattern>
         <versionFormat>${branch}-SNAPSHOT</versionFormat>
    </branch>
```

**Comment by chris-mac** [comment]
> @chris-mac your branch configuration for pull branches can be simplified to
> 
> ```
>     <branch>
>          <pattern>pull/.+</pattern>
>          <versionFormat>${branch}-SNAPSHOT</versionFormat>
>     </branch>
> ```

Thanks @qoomon think that config would give me a `/` rather than `-`? i.e in this example my GITHUB_REF would be `refs/pull/3/merge` and my desired output version would be `pull-3-SNAPSHOT`?
BTW thanks a lot for this extension, I've been manually implementing an almost identical system for years when working with Java.

**Comment by qoomon** [comment]
I tried to point that out in the readme every / is automatically replaced in version by a - automatically

**Comment by chris-mac** [comment]
> I tried to point that out in the readme every / is automatically replaced in version by a - automatically

Ah OK cool missed that thx

**Pull request merged**
