### PR TITLE
Endless loop in ModelProcessor#findMvnDir during build on the third level module in a multimodule project

### PR DESCRIPTION
**Pull request by dornwelt**
Hi @qoomon,

after the fix of Issue 34, I have one big problem during any builds on the third level module in a multimodule project. -> endless loop because the code line 245 in the ModelProcessor class. The parentPomFile is always taken from the projectModel and does not use parentModel variable.

In PR is my possible solution.

### CODE REVIEW

**Comment by qoomon** [comment]
Oh damn it, thx for reporting, will look into it right now

**Comment by qoomon** [comment]
I made some changes to your proposal and some improvements to the tests as well, may you can merge the branch pull38 into your branch before I merge the your pull request

**Comment by dornwelt** [comment]
cool, many thx!

**Comment by qoomon** [comment]
Thx again for your support.

**Pull request merged**
