### PR TITLE
change location of .git-versioned.pom.xml

### PR DESCRIPTION
**Pull request by florianli**
#28

### CODE REVIEW

**Comment by qoomon** [comment]
I think GIT_VERSIONED_POM_FILE_FOLDER should be just the 'target' folder.
We should get the 'target' folder from `MavenProject currentProject`, I will see if it is available some how.

**Comment by qoomon** [comment]
What do you think about may modifications of your PR?

**Comment by florianli** [comment]
Looks good to me.

**Comment by qoomon** [comment]
I am not sure about the file name? Do you have any suggestions? Or may I
call it just pom.xml?

**Comment by qoomon** [comment]
Please fix Tests in `src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java` you need to prefix every usage of `GIT_VERSIONED_POM_FILE_NAME` with 'target/'

**Comment by florianli** [comment]
Sorry I'm a little bit busy right now. I'm not able to respond so fast. 
The filename `.git-versioned.pom.xml` is ok. It's clear that it is not the original `pom.xml` and with `git-versioned`-prefix you can see that it generated by your extension. So again, it looks good to me.

**Pull request merged**
